# Automatically updated by the winget bot at 2022/Aug/22
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json

PackageIdentifier: Stride.Stride
Publisher: Stride
PackageName: Stride
PackageVersion: 5.0.6
License: MIT
InstallerType: exe
LicenseUrl: https://github.com/stride3d/stride/raw/master/LICENSE.md
Moniker: Stride3d
Tags:
- stride
- stride3d
- xenko
- game engine
- game development
- gamedev
- 3d
- 2d
- .NET
- dotnet
- net
- C#
- csharp
ShortDescription: Stride is an open-source MIT C# game engine designed for the future of gaming.
PackageUrl: https://stride3d.net/
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://stride3d.net/files/StrideSetup.exe
  InstallerSha256: CEF0C590BBF88C948495F8B3D0681732056A2B44F3C0169F488B265FED9AE29F
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /passive
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
